#!/bin/bash

#SBATCH --partition=gpu
#SBATCH --gpus=1
#SBATCH --job-name=NaviBenchmark
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=18
#SBATCH --time=04:00:00
#SBATCH --output=../job_logs/install-dep-%A.out

module purge
module load 2022
module load Anaconda3/2022.05

cd $HOME/Timetuning_v2
export BASE_CACHE_DIR="$SCRATCH_LOCAL/Timetuning_v2"
export PYTHONPATH= $HOME/Timetuning_v2/:$PYTHONPATH
# Activate your environment
source activate timet
pip install pycocotools
